language: node_js
node_js:
  - "stable"
sudo: false
env: REACT_VERSION=15.3.x
matrix:
  include:
    # These versions run different jobs in which we `yarn add` other releases
    # of react (& friends) to run our test suite against those as well
    - env: REACT_VERSION=^0.14.9
    - env: REACT_VERSION=15.x
cache: yarn
install:
  - yarn
  - yarn add react@$REACT_VERSION react-dom@$REACT_VERSION react-addons-test-utils@$REACT_VERSION
